### ISSUE TITLE
Add Zenodo DOI for poster as soon as it's finished.

### ISSUE THREAD

**Issue by TheChymera** [con/opfvta-reexecution#62]
Currently the poster draft reuses the DOI of RepSeP. We should update it.

**Comment by yarikoptic** [comment]
FWIW I enabled integration with zenodo:

![image](https://github.com/con/opfvta-reexecution/assets/39889/5e50ff0b-77aa-40ed-bd1c-30d4b93dc999)

so generation of release here should generate entry/DOI on zenodo to reuse

**Comment by yarikoptic** [comment]
BTW, for zenodo you might like to prepare proper CITATION.cff , see https://citation-file-format.github.io/, which is now IIRC supported by zenodo, so you get a nice title and list of authors etc.

**Comment by TheChymera** [comment]
@yarikoptic `CITATION.cff` seems to already require a DOI. If I need it *before* I trigger the zenodo DOI via a release, it means I need to create one manually anyway, right?

**Comment by TheChymera** [comment]
Finished during pre-SfN meeting.
