### ISSUE TITLE
Article lacks a pointer to this repository 

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-reexecution#66]
how someone is supposed to reexecute it then if there is no way to get this entire setup?

**Comment by yarikoptic** [comment]
may be even add explicit mentioning of README as the ultimate source of instructions on how to execute.

Also I think we better tag some specific version as of e.g. point of submission (e.g. 1.20240119.0) and reference that specific version in the article (not quite a chicken/egg issue since we can always talk about a tag yet to be pushed)

**Comment by TheChymera** [comment]
@yarikoptic there was already a reference, but we had not used it. Solved in https://github.com/con/opfvta-reexecution/commit/840e5a1e1f1c40fcd868fbe395908a56649570d1 .
